### ISSUE TITLE
Prometheus golang_client syntax errors

### ISSUE THREAD

**Issue by AmandaHassoun** [promqueen/maillog_exporter#1]
Hey, I'm wondering if you ran into any syntax errors during compilation? Because I'm seeing the following when I run `make build`:

src/github.com/prometheus/client_golang/prometheus/registry.go:398: syntax error: unexpected range, expecting {
src/github.com/prometheus/client_golang/prometheus/registry.go:512: non-declaration statement outside function body
src/github.com/prometheus/client_golang/prometheus/registry.go:513: non-declaration statement outside function body
src/github.com/prometheus/client_golang/prometheus/registry.go:514: syntax error: unexpected }

Thanks!

**Comment by thomersch** [comment]
Compiles cleanly on my machine and on CI, so maybe there is be a problem in your setup.

Which version of Go are you using? Because it looks like it doesn't take the checked in vendors into consideration.

**Comment by AmandaHassoun** [comment]
So I was using the wrong version! Thank you
